name: Build
on:
  push:
    branches: ['**']
  pull_request:
env:
  app_id: inputstream.tempo

jobs:
  build:
    runs-on: ubuntu-latest
    name: Linux x86_64 / Kodi 21
    steps:
    - name: Checkout addon
      uses: actions/checkout@v5
      with:
        path: ${{ env.app_id }}

    - name: Checkout Kodi
      uses: actions/checkout@v5
      with:
        repository: xbmc/xbmc
        ref: Omega
        path: xbmc
        sparse-checkout: |
          version.txt
          xbmc/interfaces/json-rpc/schema/version.txt
          cmake/
          xbmc/addons/AddonBindings.cmake
          xbmc/addons/kodi-dev-kit/include/kodi/
        sparse-checkout-cone-mode: false
        fetch-depth: 1

    - name: Install dependencies
      run: sudo apt-get update -qq && sudo apt-get install -y autopoint nasm

    - name: Build
      run: |
        ${{ github.workspace }}/${app_id}/scripts/build.sh \
          --os linux \
          --arch x86_64 \
          --kodi 21 \
          --kodi-src ${{ github.workspace }}/xbmc \
          --output ${{ github.workspace }}/artifacts \
          --jobs $(getconf _NPROCESSORS_ONLN)

    - name: Upload zip
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.app_id }}-linux-x86_64-kodi21
        path: ${{ github.workspace }}/artifacts/*.zip
        if-no-files-found: error
